# Generated by Django 3.2.9 on 2021-12-02 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranspartationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=225, verbose_name='Имя компании')),
                ('train_number', models.CharField(max_length=255, unique=True, verbose_name='Номера поезда')),
                ('date', models.DateField(blank=True, editable=False, null=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operators_transpartationlog_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_operators_transpartationlog_set', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Лог транспартировки',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TranspartationCarriageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cargo_weight', models.CharField(max_length=225, verbose_name='Вес груза')),
                ('carriage_number', models.CharField(max_length=255, unique=True, verbose_name='Номер состава')),
                ('carriage_type', models.CharField(max_length=255, unique=True, verbose_name='Тип вагона')),
                ('carriage_photo', models.ImageField(height_field=100, upload_to='carriage', width_field=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operators_transpartationcarriagelog_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_operators_transpartationcarriagelog_set', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('train', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='operators.transpartationlog', verbose_name='Поезд')),
            ],
            options={
                'verbose_name': 'Лог записи вагонов',
            },
        ),
        migrations.CreateModel(
            name='CargoQualityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quality_control', models.IntegerField(verbose_name='Качество груза')),
                ('carriage_photo', models.ImageField(height_field=100, upload_to='carriage_quality', width_field=100)),
                ('carriage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carriage', to='operators.transpartationcarriagelog', verbose_name='Вагон')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operators_cargoqualityassessment_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_operators_cargoqualityassessment_set', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
