# Generated by Django 3.2.9 on 2021-12-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transpartationlog',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
