# Generated by Django 3.2.9 on 2021-12-03 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operators', '0002_alter_transpartationlog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationCarriageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cargo_weight', models.CharField(max_length=225, verbose_name='Вес груза')),
                ('carriage_number', models.CharField(max_length=255, unique=True, verbose_name='Номер состава')),
                ('carriage_type', models.CharField(max_length=255, unique=True, verbose_name='Тип вагона')),
                ('carriage_photo', models.ImageField(height_field=100, upload_to='carriage', width_field=100)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operators_transportationcarriagelog_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_operators_transportationcarriagelog_set', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Лог записи вагонов',
            },
        ),
        migrations.CreateModel(
            name='TransportationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=225, verbose_name='Имя компании')),
                ('train_number', models.CharField(max_length=255, unique=True, verbose_name='Номера поезда')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_operators_transportationlog_set', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_operators_transportationlog_set', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Лог транспартировки',
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='transpartationcarriagelog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transpartationcarriagelog',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='transpartationcarriagelog',
            name='train',
        ),
        migrations.DeleteModel(
            name='TranspartationLog',
        ),
        migrations.AddField(
            model_name='transportationcarriagelog',
            name='train',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train', to='operators.transportationlog', verbose_name='Поезд'),
        ),
        migrations.AlterField(
            model_name='cargoqualityassessment',
            name='carriage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carriage', to='operators.transportationcarriagelog', verbose_name='Вагон'),
        ),
        migrations.DeleteModel(
            name='TranspartationCarriageLog',
        ),
    ]
