# Generated by Django 3.2.9 on 2021-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0003_auto_20211203_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargoqualityassessment',
            options={'verbose_name': 'Контроль качества вагонов'},
        ),
        migrations.AlterField(
            model_name='cargoqualityassessment',
            name='carriage_photo',
            field=models.ImageField(height_field=1000, upload_to='carriage_quality', width_field=1000),
        ),
        migrations.AlterField(
            model_name='transportationcarriagelog',
            name='cargo_weight',
            field=models.CharField(max_length=255, verbose_name='Вес груза'),
        ),
        migrations.AlterField(
            model_name='transportationlog',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя компании'),
        ),
    ]
