# Generated by Django 3.2.9 on 2021-12-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0006_auto_20211203_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoqualityassessment',
            name='carriage_photo',
            field=models.ImageField(upload_to='carriage_quality'),
        ),
        migrations.AlterField(
            model_name='transportationcarriagelog',
            name='carriage_photo',
            field=models.ImageField(upload_to='carriage'),
        ),
    ]
