# Generated by Django 3.2.9 on 2021-12-03 07:13

from django.db import migrations, models
import operators.models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0007_auto_20211203_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_url', models.ImageField(upload_to=operators.models.upload_to)),
                ('url_to_upload', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
