# Generated by Django 3.2.9 on 2021-12-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0008_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoqualityassessment',
            name='carriage',
        ),
        migrations.RemoveField(
            model_name='cargoqualityassessment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cargoqualityassessment',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
        migrations.AlterModelOptions(
            name='transportationcarriagelog',
            options={'verbose_name': 'Вагон ', 'verbose_name_plural': 'Лог записи вагонов'},
        ),
        migrations.AlterModelOptions(
            name='transportationlog',
            options={'ordering': ['date'], 'verbose_name': 'Поезд', 'verbose_name_plural': 'Лог транспортировки'},
        ),
        migrations.AddField(
            model_name='transportationcarriagelog',
            name='carriage_quality_photo',
            field=models.ImageField(null=True, upload_to='carriage_quality'),
        ),
        migrations.AddField(
            model_name='transportationcarriagelog',
            name='quality_control',
            field=models.IntegerField(null=True, verbose_name='Качество груза'),
        ),
        migrations.AlterField(
            model_name='transportationcarriagelog',
            name='carriage_photo',
            field=models.ImageField(null=True, upload_to='carriage'),
        ),
        migrations.DeleteModel(
            name='CargoQualityAssessment',
        ),
    ]
