# Generated by Django 3.2.9 on 2021-12-03 12:13

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0010_alter_transportationcarriagelog_carriage_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationcarriagelog',
            name='carriage_quality_photo',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='carriage'),
        ),
    ]
