# Generated by Django 3.2.9 on 2021-12-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0012_alter_transportationcarriagelog_carriage_quality_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportationlog',
            old_name='name',
            new_name='name_organization',
        ),
    ]
