# Generated by Django 3.2.9 on 2021-12-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0014_carriagephoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationcarriagelog',
            name='carriage_photo',
        ),
        migrations.RemoveField(
            model_name='transportationcarriagelog',
            name='carriage_quality_photo',
        ),
    ]
